"""Renamed amount_base

Revision ID: 164b59ec1701
Revises: 0dbcf7e898fd
Create Date: 2025-11-05 16:57:11.052888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164b59ec1701'
down_revision: Union[str, Sequence[str], None] = '0dbcf7e898fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('amount_in_default', sa.BigInteger(), nullable=False))
    op.drop_column('accounts', 'amount_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('amount_base', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'amount_in_default')
    # ### end Alembic commands ###
