"""renamed active to is_active

Revision ID: ac7eb211ff9e
Revises: 33abef141e54
Create Date: 2026-01-14 10:18:07.419848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7eb211ff9e'
down_revision: Union[str, Sequence[str], None] = '33abef141e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('chat_sessions', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('chat_sessions', 'is_active')
    # ### end Alembic commands ###
